version: "3"

services:
  mariadb:
    image: mariadb:inc
    build: ./mariadb/
    restart: unless-stopped
    volumes:
      - ~/data/maria:/var/lib/mysql
    networks:
      inception:
    ports:
      - "3306:3306"

  nginx:
    image: nginx:inc
    build:
      context: ./nginx/
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - ~/data/wp:/var/www/wordpress/
    networks:
      inception:
    depends_on:
      - wordpress
    extra_hosts:
      - "tcosse.42.fr:127.0.0.1"

  wordpress:
    image: wordpress:inc
    build: ./wordpress/
    restart: unless-stopped
    volumes:
      - ~/data/wp:/var/www/wordpress/
    networks:
      inception:
    depends_on:
      - mariadb
    ports:
      - "9000:9000"

networks:
  inception:
    driver: bridge
